### ISSUE TITLE
Added to Mana yet?

### ISSUE THREAD

**Issue by edlovesiraq** [sensepost/hostapd-mana#14]
Has this been added to Mana's functionality yet?

**Comment by sundhaug92** [comment]
What?

**Comment by singe** [comment]
hostapd-2.6 branch hasn't been added to mana yet. There's an issue with the ssid filter than needs fixing first. Pull requests welcome :)

**Comment by mpkosewski** [comment]
well how does one build this? hostapd 2.3 and 2.6 wont end in successful "make" T_T 

`../src/crypto/tls_openssl.c: In function ‘tls_load_ca_der’:
../src/crypto/tls_openssl.c:1540:40: error: dereferencing pointer to incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
  lookup = X509_STORE_add_lookup(ssl_ctx->cert_store,
                                        ^~
../src/crypto/tls_openssl.c: In function ‘tls_connection_get_keys’:
../src/crypto/tls_openssl.c:2532:24: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
  if (ssl == NULL || ssl->s3 == NULL || ssl->session == NULL)
`
