### ISSUE TITLE
Unable to compile on Kali Rolling (RPi2) [Lightdm] 

### ISSUE THREAD

**Issue by Mas0x** [sensepost/hostapd-mana#15]
root@kali:~/hostapd-2.6/hostapd# make && make install
../src/drivers/driver_nl80211.c:17:31: fatal error: netlink/genl/genl.h: No such file or directory
 #include <netlink/genl/genl.h>
                               ^
compilation terminated.
Makefile:1036: recipe for target '../src/drivers/driver_nl80211.o' failed
make: *** [../src/drivers/driver_nl80211.o] Error 1

Can you assist?

**Comment by singe** [comment]
Use the hostapd-2.6 branch
