### ISSUE TITLE
awus036ach requirements

### ISSUE THREAD

**Issue by JBelinchon** [sensepost/hostapd-mana#16]
As I can read on the requirements section, the interface needs those modes:
Supported interface modes:
         * IBSS
         * managed
         * AP
         * AP/VLAN
         * monitor
         * mesh point

I am testting the adapter awus036ach using the official Kali drivers and I can see the drivers only support the following modes: 

Supported interface modes:
        * IBSS
        * managed
        * AP
        * monitor
        * P2P-client
        * P2P-GO

Looks like it does not support  AP/VLAN / mesh point

Am I missing some mana funcionality without those two modes (AP/VLAN / mesh point)?

Best Regards !!

**Comment by singe** [comment]
Nah, "AP" will cover it

**Comment by mpkosewski** [comment]
ah ha! good to know !I just got the awus036ach and it works but the "mana" part doesn't look like it? it doesn't show the normal probe broadcasts or whatnot. Not sure why? other alfa devices do it just fine. @_@

**Comment by JBelinchon** [comment]
Yeah, this is that I discovered in my testings with that device. But looks like something cosmetic, mana has effect despite the probe broadcast is not showing.

**Comment by mpkosewski** [comment]
Wait.... Really?? I never let it run long enough to check xD omg I gotta check it again

**Comment by mpkosewski** [comment]
I checked a few times and it only brings up the Rogue  AP and that functions fine. But when I set the mana-loud option to 1, it doesn't show nor broadcast the other probed wifi like it does with the other alfa adapters =/

**Comment by singe** [comment]
If someone wants to sponsor me a device I can test it :) Otherwise, this is with the device not hostapd-mana, so I'm closing it here.
