### ISSUE TITLE
Always return EAP Success

### ISSUE THREAD

**Issue by Lexus89** [sensepost/hostapd-mana#17]
Hi,

I can't seem to find an option like hostapd-wpe in here to always return EAP Success. Would be a nice addition, or is it already in there and have i overlooked something in the code.. Will it still work with FreeRADIUS-WPE and using hostapd-mana just as authenticator?

**Comment by singe** [comment]
I think it was done way back in 2014, I was spelunking through https://github.com/sensepost/hostapd-mana/commit/a212242c17389685f91e3a2ed4cc02e78e815be5 to check, but can't obviously see it. I definitely saw it in WPE circa 2015 when comparing the code, but can't remember what I did with it.

**Comment by Lexus89** [comment]
Thanks for your response, from what i understand this needs to be verified still? This return success could also be implemented for WEP. As far as i know this hasnt been implemented by anyone else before. Hostapd-mana is the goto tool for this stuff, so happy to see it getting better and better.

**Comment by singe** [comment]
Just did some testing and it wasn't working. Added https://github.com/sensepost/hostapd-mana/commit/11c121ec31fde2d653b814b6e545e98e9a02f862 to fix it. Will do it for the other EAP types as I refactor the WPE code in the next few days.
