### ISSUE TITLE
Whitelist ACL not working

### ISSUE THREAD

**Issue by ixty** [sensepost/hostapd-mana#18]
Hello,
your patch to hostapd's ACL loading to support masks broke the whitelist functionality (and probably blacklist as well, although i havent tested it).

You can fix it by changing the following code:
hostapd/config_file.c:230
```
    hwaddr_aton("ff:ff:ff:ff:ff:ff", mask); //No mask specified to add a "no change" mask
```
change it to
```
    {
        hwaddr_aton("ff:ff:ff:ff:ff:ff", mask); //No mask specified to add a "no change" mask
        for (i=0; i<ETH_ALEN; i++)
            transform[i] = addr[i];
    }
```

**Comment by singe** [comment]
Thanks! Fixed in https://github.com/sensepost/hostapd-mana/commit/38d7a2e1d6ee174836956ebeeb01ade711273fdc
