### ISSUE TITLE
Maybe I miss something...

### ISSUE THREAD

**Issue by Zibri** [sensepost/hostapd-mana#19]
I tried with mana enabled...
The access point is created and works.
My 3 phones search for home network and the hostapd sees then and write that it's seanding the probe.
But none of the phones tries to connect to it unless I tell them to.

**Comment by singe** [comment]
I can't really debug that for you without more information. My gut feel is that there is a mismatch of your home network and rogue AP's configs e.g. your home is WPA/2 and your rogue is open. Ideally, please provide some pcaps of your target network beacon or probe response frames as well as your hostapd config.

**Comment by Zibri** [comment]
Correct. And That's the problem.

But I thought that the AP could reconfigure itself in the same way and accept my phone.

Nevermind. And thatnks for the reply.

I have an off-topic question:

as a security researcher, I am studying wifi p2p and I found one strange thing:

Screen mirroring works using wifi p2p (if the display/tv is on a different network than the phone).

When a phone mirrors it's screen, the device I am anayzing, does not prompt for authorization (!).

If I try from a linux box, the best I have got is that the device asks me to go to settings and to connect manually to the phone.

Since both (pc and the display device) run linux, and I have root access on both, how can I understand and replicate the wifi p2p "handshake" between phone and device?

I searched everywhere with google and the best page I found was this one detailing the connection between some ti embedded devices.

http://processors.wiki.ti.com/index.php/WiFi_Direct_Configuration_Scripts

Can you help me with that?

**Comment by singe** [comment]
To your first question, you can configure multiple networks, and the device will join the most appropriate. Here's an example config doing open and EAP https://github.com/sensepost/mana/blob/master/run-mana/conf/hostapd-mana-all.conf you can add PSK in too.
