### ISSUE TITLE
Taxonomy: No taxonomy output sent to mana_outfile

### ISSUE THREAD

**Issue by adde88** [sensepost/hostapd-mana#22]
I've compiled the latest commit, with CONFIG_TAXONOMY enabled.
Tested it on my Kali Linux laptop (x64), and on my WiFi Pineappple (OpenWRT).

There's no taxonomy output being sent to "mana_outfile".
If i simultaneously launch the compiled hostapd_cli, it is clearly compiled with taxonomy, as i can request taxonomy signature from a station.

The mana_outfile simply looks like this:
```
root@fsociety:~# cat /tmp/hostapd-mana.out
72:10:6a:78:d7:84, <Broadcast>, 1
4c:b1:99:3b:89:4a, <Broadcast>, 0
26:79:67:9b:27:79, <Broadcast>, 1
4c:b1:99:3b:89:4a, <Broadcast>, 0
b4:9c:df:51:ab:d4, Lovmo, 0
```

If i'm not mistaken it should look like this:
```<MAC>, <SSID>, <Random 1, or not 0>, <TAXONOMY>```

**Comment by singe** [comment]
Did you set the relevant fields in the config as per the sample?

https://github.com/sensepost/hostapd-mana/blob/a3c668bcf91625bd20d9994c44f92ecedd53643e/hostapd/hostapd.conf#L39

https://github.com/sensepost/hostapd-mana/blob/a3c668bcf91625bd20d9994c44f92ecedd53643e/hostapd/hostapd.conf#L39
https://github.com/sensepost/hostapd-mana/blob/a3c668bcf91625bd20d9994c44f92ecedd53643e/hostapd/hostapd.conf#L39
https://github.com/sensepost/hostapd-mana/blob/a3c668bcf91625bd20d9994c44f92ecedd53643e/hostapd/hostapd.conf#L39
> On 19 May 2018, at 14:11, Andreas Nilsen <notifications@github.com> wrote:
> 
> I've compiled the latest commit, with CONFIG_TAXONOMY enabled.
> Tested it on my Kali Linux laptop (x64), and on my WiFi Pineappple (OpenWRT).
> 
> There's no taxonomy output being sent to "mana_outfile".
> If i simultaneously launch the compiled hostapd_cli, it is clearly compiled with taxonomy, as i can request taxonomy signature from a station.
> 
> The mana_outfile simply looks like this:
> 
> root@fsociety:~# cat /tmp/hostapd-mana.out
> 72:10:6a:78:d7:84, <Broadcast>, 1
> 4c:b1:99:3b:89:4a, <Broadcast>, 0
> 26:79:67:9b:27:79, <Broadcast>, 1
> 4c:b1:99:3b:89:4a, <Broadcast>, 0
> b4:9c:df:51:ab:d4, Lovmo, 0
> If i'm not mistaken it should look like this:
> <MAC>, <SSID>, <Random 1, or not 0>, <TAXONOMY>
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


https://github.com/sensepost/hostapd-mana/blob/a3c668bcf91625bd20d9994c44f92ecedd53643e/hostapd/hostapd.conf#L39

**Comment by adde88** [comment]
Damn. I could have sworn i tested it with them enabled the first time.
Though, that version migh have been compiled without taxonomy enabled.
Thanks! :)
And sorry for adding an "issue" out of something i clearly should have noticed 👍
