### ISSUE TITLE
Porting to OpenWRT

### ISSUE THREAD

**Issue by LucaBongiorni** [sensepost/hostapd-mana#3]
I am evaluating to port hostapd-mana to Openwrt in order to make it run under ZSUN AP [1]
I have also noticed that someone already manage to port a very similar weaponized version of hostapd (i.e hostapd-wpe) to openwrt but applying manually some patches [2].
**
I am writing here in case someone is interested as well or if already tried the porting and eventually succeded.**

[1] https://forum.openwrt.org/viewtopic.php?pid=313458
[2] https://www.acrylicwifi.com/en/blog/hostapd-wpe-openwrt-barrier-breaker/

**Comment by singe** [comment]
Check the forks. Someone did port it. It requires some weird patches available from the OpenWRT repos that will be a nightmare to maintain going forward so I chose not to merge them. If you can find a more sustainable set of patches or clean them up I'd be more than happy to help maintain them going forward.

**Comment by LucaBongiorni** [comment]
I guess you are talking about https://github.com/lostincynicism/hostapd-mana ?
I see two sets of patches: one for openwrt and some for Realtek chipsets.
If this is the fork you were talking about, I will contact its owner to ask why he applied noscan patch and if he succeded to crosscompile it on openWRT... I will start working on it and see how to keep it simple and clean, in order to be mantained easily.

**Comment by singe** [comment]
Yes that's it. The noscan patch makes sense (I use it) and I should probably add it since mana isn't about being a long term or well behaved AP ;)

Truthfully, it's the Realtek patches that were problematic, but you don't need those. So maybe there's an easy port?

**Comment by LucaBongiorni** [comment]
Good, now I have a starting point.
I'll apply thay noscan patch to your main branch and try to Xcompile it
with openwrt SDK and pray for the best. ;)

Hope to succeed and be back soon.

**Comment by strasharo** [comment]
Hey @LucaBongiorni , I'm also interested in the Zsun device. Does the wireless in it support injection currently?

**Comment by LucaBongiorni** [comment]
@strasharo Since is an Atheros AR9331 it should support injection.
Sadly I have no much time to play with it during these days...

**Comment by strasharo** [comment]
Yay, that's awesome. Is OpenWRT  running stable on it currently, I see that there's no upstream support yet?

**Comment by LucaBongiorni** [comment]
Since I am having problems to compile this repo with openWRT SDK... I thought to change approach and patch manually hostapd v.2.2 for OpenWRT...
@singe Is this http://singe.za.net/utils/hostapd-karma/hostapd-2.0-karma.patch the latest version of your patch?

**Comment by cibelix** [comment]
Hi all;

I'm new on Zsun. I buy one and flash OpenWrt on it. 
Any progress about mana on Zsun? I'm not compile skills sorry, but with apropiate guide I can do.

Thanks all

Fernando

**Comment by adde88** [comment]
I've managed to port it to the ar71xx, and it's working great on both of my 6.th generation wifi pineapples.
Source code is available at my repo: https://github.com/adde88/hostapd-mana-openwrt
IPK files are also there if you don't want to cross-compile everything yourself.

I'm working on improving both the install procedure and the launch-script.
So suggestions are appreciated! :)

**Comment by LucaBongiorni** [comment]
That's cool!
I'll try asap on my ZSUN.
If by any chance you have a ZSUN (very cool cheap Atheros hw)... let me
know.

Back in time, I managed to push Pineapple Nano fw into it, but didn't have
much time for full testing though.

On Oct 25, 2016 8:12 AM, "Andreas Nilsen" <notifications@github.com> wrote:

I've managed to port it to the ar71xx, and it's working great on both of my
6.th generation wifi pineapples.
Source code is available at my repo: https://github.com/adde88/
hostapd-mana-openwrt
IPK files are also there if you don't want to cross-compile everything
yourself.

I'm working on improving both the install procedure and the launch-script.
So suggestions are appreciated! :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sensepost/hostapd-mana/issues/3#issuecomment-255945665>,
or mute the thread

**Comment by adde88** [comment]
Yeah, the ZSUN. I've read alot about it. I haven't gotten my hands on it yet.
But perhaps i should hit ebay up and order one. I love fiddling with new stuff.
Especially Atheros chips.
Thanks for the tip. :)

**Comment by LucaBongiorni** [comment]
No problem :)
I didn't have chance yet to try replacing the original hostapd with yours within the ZSUN... but is in my todo list. ;]
If I have news I'll keep you informed!

**Comment by adde88** [comment]
If you can drop me a link to the SDK you are using on the ZSUN, i could try compiling it for you, and then upload the working SDK to you, or the binaries if you'd like. =)

**Comment by LucaBongiorni** [comment]
Hi,
Here it is https://github.com/Emeryth/openwrt-zsun
The tricky part of ZSUN, is that we have no straight ETH ot UART connection (unless we solder them on the PCB of course). 
Thus trying to replace the original hostapd with the hostapd-mana is quite tricky only through the wifi. 
But so far, I was able to push the WifiPineapple NANO FW and was working. OF course it needed to tweak some things (like the first boot of the NANO, which asks to press the reset button or deactivate the wifi).
But overall seems doable as well.
