### ISSUE TITLE
libssl.so.1.0.0 Not Found

### ISSUE THREAD

**Issue by ryanvillarreal** [sensepost/hostapd-mana#30]
Getting the following error message when attempting to run hostapd on Kali Linux 2018.3. 

```
./hostapd: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

I tried linking the newer libssl.so1.0.2 to libssl.so1.0.0 with no luck.  Any help with be appreciated.

**Comment by singe** [comment]
Did you follow these instructions? https://github.com/sensepost/hostapd-mana/wiki/Installing#kali

**Comment by ryanvillarreal** [comment]
Building from source worked.  I'll close.

**Comment by singe** [comment]
Glad that worked.
