### ISSUE TITLE
Thinkpad T440p+Ubuntu 14+VirtualBox+Kali+Alfa AWU

### ISSUE THREAD

**Issue by mayday77** [sensepost/hostapd-mana#4]
Hello to everyone 
God verrrrry painful issue
## Trying to install mana and get tons of errors (yes,yes,i know about error in my DNA ) 

root@kali:~/Downloads/mana-master# ./kali-install.sh 
SensePost Mana Installer
[+] This is not a very good installer, it makes a lot of assumptions
[+] It assumes you are running Kali
[+] If you are worried about that, hit Ctl-C now, or hit Enter to continue

Reading package lists... Done
Building dependency tree  
Reading state information... Done
Package libnl-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libnl-dev' has no installation candidate
make -C hostapd-mana/hostapd/
make[1]: Entering directory '/root/Downloads/mana-master/hostapd-mana/hostapd'
  CC  main.c
  CC  config_file.c
  CC  ../src/ap/hostapd.c
  CC  ../src/ap/wpa_auth_glue.c
  CC  ../src/ap/drv_callbacks.c
  CC  ../src/ap/ap_drv_ops.c
  CC  ../src/ap/utils.c
  CC  ../src/ap/authsrv.c
  CC  ../src/ap/ieee802_1x.c
  CC  ../src/ap/ap_config.c
  CC  ../src/ap/eap_user_db.c
  CC  ../src/ap/ieee802_11_auth.c
  CC  ../src/ap/sta_info.c
  CC  ../src/ap/wpa_auth.c
  CC  ../src/ap/tkip_countermeasures.c
  CC  ../src/ap/ap_mlme.c
  CC  ../src/ap/wpa_auth_ie.c
  CC  ../src/ap/preauth_auth.c
  CC  ../src/ap/pmksa_cache_auth.c
  CC  ../src/ap/ieee802_11_shared.c
  CC  ../src/ap/beacon.c
  CC  ../src/drivers/drivers.c
  CC  ../src/utils/eloop.c
  CC  ../src/utils/common.c
  CC  ../src/utils/wpa_debug.c
  CC  ../src/utils/wpabuf.c
  CC  ../src/utils/os_unix.c
  CC  ../src/utils/ip_addr.c
  CC  ../src/common/ieee802_11_common.c
  CC  ../src/common/wpa_common.c
  CC  ../src/eapol_auth/eapol_auth_sm.c
  CC  ../src/eapol_auth/eapol_auth_dump.c
  CC  ../src/radius/radius.c
  CC  ../src/radius/radius_client.c
  CC  ../src/radius/radius_das.c
  CC  ../src/ap/vlan_init.c
  CC  ctrl_iface.c
  CC  ../src/ap/ctrl_iface_ap.c
  CC  ../src/crypto/md5.c
  CC  ../src/ap/iapp.c
  CC  ../src/ap/peerkey_auth.c
  CC  ../src/drivers/driver_hostap.c
  CC  ../src/drivers/driver_wired.c
../src/drivers/driver_nl80211.c:19:31: fatal error: netlink/genl/genl.h: No such file or directory
compilation terminated.
Makefile:891: recipe for target '../src/drivers/driver_nl80211.o' failed
make[1]: **\* [../src/drivers/driver_nl80211.o] Error 1
make[1]: Leaving directory '/root/Downloads/mana-master/hostapd-mana/hostapd'
Makefile:3: recipe for target 'all' failed
make: **\* [all] Error 2
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'python-scapy' instead of 'scapy'
apache2 is already the newest version (2.4.18-1).
apache2 set to manually installed.
asleap is already the newest version (2.2-1kali7).
asleap set to manually installed.
dsniff is already the newest version (2.4b1+debian-22.1+b2).
dsniff set to manually installed.
iptables is already the newest version (1.4.21-2+b1).
macchanger is already the newest version (1.7.0-5.3).
macchanger set to manually installed.
metasploit-framework is already the newest version (4.11.7-0kali1).
metasploit-framework set to manually installed.
procps is already the newest version (2:3.3.11-3).
python-dnspython is already the newest version (1.12.0-1).
python-dnspython set to manually installed.
python-pcapy is already the newest version (0.10.8-1+b1).
python-pcapy set to manually installed.
python-scapy is already the newest version (2.2.0-1kali1).
python-scapy set to manually installed.
sslsplit is already the newest version (0.4.11+dfsg-2).
sslsplit set to manually installed.
stunnel4 is already the newest version (3:5.29-1).
stunnel4 set to manually installed.
Suggested packages:
  resolvconf
The following NEW packages will be installed:
  dnsmasq tinyproxy
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 98.8 kB of archives.
After this operation, 219 kB of additional disk space will be used.
Get:1 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main i386 dnsmasq all 2.75-1 [15.9 kB]
Get:2 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main i386 tinyproxy i386 1.8.3-3+b1 [82.9 kB]
Fetched 98.8 kB in 1s (75.2 kB/s)
Selecting previously unselected package dnsmasq.
(Reading database ... 309871 files and directories currently installed.)
Preparing to unpack .../dnsmasq_2.75-1_all.deb ...
Unpacking dnsmasq (2.75-1) ...
Selecting previously unselected package tinyproxy.
Preparing to unpack .../tinyproxy_1.8.3-3+b1_i386.deb ...
Unpacking tinyproxy (1.8.3-3+b1) ...
Processing triggers for systemd (228-4) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up dnsmasq (2.75-1) ...
update-rc.d: We have no instructions for the dnsmasq init script.
update-rc.d: It looks like a network service, we disable it.
insserv: warning: current start runlevel(s) (empty) of script `dnsmasq' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script`dnsmasq' overrides LSB defaults (0 1 6).
Setting up tinyproxy (1.8.3-3+b1) ...
update-rc.d: As per Kali policy, tinyproxy init script is left disabled.
insserv: warning: current start runlevel(s) (empty) of script `tinyproxy' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script`tinyproxy' overrides LSB defaults (0 1 6).
Processing triggers for systemd (228-4) ...
# Create the target directories

install -d -m 755 /usr/share/mana-toolkit/www
install -d -m 755 /usr/share/mana-toolkit/crackapd
install -d -m 755 /usr/share/mana-toolkit/firelamb
install -d -m 755 /usr/share/mana-toolkit/sslstrip-hsts/sslstrip2
install -d -m 755 /usr/share/mana-toolkit/sslstrip-hsts/sslstrip2/sslstrip
install -d -m 755 /usr/share/mana-toolkit/sslstrip-hsts/dns2proxy
install -d -m 755 /usr/share/mana-toolkit/net-creds
install -d -m 755 /usr/share/mana-toolkit/cert
install -d -m 755 /usr/share/mana-toolkit/run-mana
install -d -m 755 /usr/lib/mana-toolkit/
install -d -m 755 /var/lib/mana-toolkit/sslsplit
install -d -m 755 /etc/mana-toolkit/
install -d -m 755 /etc/apache2/sites-available/
# Install configuration files

install -m 644 run-mana/conf/\* /etc/mana-toolkit/
install -m 644 crackapd/crackapd.conf /etc/mana-toolkit/
install -m 644 apache/etc/apache2/sites-available/\* /etc/apache2/sites-available/
# Install the hostapd binary

install -m 755 hostapd-mana/hostapd/hostapd /usr/lib/mana-toolkit/
install: cannot stat ‘hostapd-mana/hostapd/hostapd’: No such file or directory
Makefile:6: recipe for target 'install' failed
make: **\* [install] Error 1
## [+] All done, I think, run one of the run-mana/start-*.sh scripts now

Actually , im close to pay over paypal to person who will solve this problem to me.

**Comment by singe** [comment]
On latest kali-rolling just apt-get install mana-toolkit

For other distros check the last release, it has binary packages.

Your complication error is because you don't have the new libnl-3 libs.

**Comment by mayday77** [comment]
Thank you so much for reply.
Got a Kali-rolling distro,running,updated,everything ok. 
Installed mana,no errors.
When starting,getting message about error on nl80211: could not configure driver mode / nl80211 driver initialization filed.  Hostapd_free_hap_data : interface wlan0 wasn't startet. 
god damn it !
p.s. Alfa visible on the kali , i've edit .conf and set WLAN0 as primary
Thank you!

**Comment by singe** [comment]
This is most often because network-manager is running or something else is using the card. Try /etc/init.d/network-manager stop and retry. Bear in mind this will kill you eth0 and break your upstream configs, there's a few precious replies where I showed how to exclude the wifi card from network manager but I'm not in a place to find them just now.

**Comment by great9** [comment]
You're missing some dependencies, don't have a kali box handy right now so you might want to check "apt-cache search netlink" and install the dev packages
