### ISSUE TITLE
Windows client can connect but not IOS/Android

### ISSUE THREAD

**Issue by q00td** [sensepost/hostapd-mana#59]
Hello and nice to meet you,

Bit a of a newbie regarding wireless networks so excuse me if my questions seems lacking.

I'v been trying to set-up an open access point using the following configuration: 

interface=wlan0
ssid=mana
channel=1
hw_mode=g

My windows device connect just fine but not my IOS/android devices.
They all three of them seems to initiate and connect, but only the laptop stay connected, any idea what it could be ?

wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA a0 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED a0
wlan0: STA a0 RADIUS: starting accounting session AB9AE9DBB65AB603
wlan0: STA 8e IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 8e
wlan0: STA 8e RADIUS: starting accounting session CAA0662748A95D6B

**Comment by cablethief** [comment]
Are you running a DHCP server as well? Might be the mobile devices expect to get given an IP and if not they disconnect

**Comment by q00td** [comment]
It might be that ! 
Was not expecting the device waiting for an adress from a DHCP server, i will try that and let you know.

By the way i'm using an AWUS1900

**Comment by q00td** [comment]
Thanks for the hint, it was indeed the DHCP server.
For those who might struggle with the same issue here is a link that helped:
https://doc.ubuntu-fr.org/hostapd

**Comment by cablethief** [comment]
Yes, phones for your convenience really just care about getting you internet, so they will try roam to the next thing if they don't get an IP or internet typically. There is another project called create_ap or now called linux-router (I think) that handles that. I have my own fork berate_ap which is to introduce all the mana attacks and some EAP stuff, that handles DHCP for you.
