### ISSUE TITLE
Update WPA/2 handshake hashcat format from -m2500 to -m22000

### ISSUE THREAD

**Issue by Reelix** [sensepost/hostapd-mana#60]
Attempting to crack a saved hash on the latest version of hashcat returns the following error:

> The plugin 2500 is deprecated and was replaced with plugin 22000. For more details, please read: https://hashcat.net/forum/thread-10253.html

Whilst these formats can be converted manually, it would be nice if the tool captured in the updated 22000 format instead.

**Comment by singe** [comment]
Please update to the latest, this was done in https://github.com/sensepost/hostapd-mana/commit/8853d5ac7f97b140b7899d2cf074eca921e55c3b
