### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by gresskar** [sensepost/hostapd-mana#61]
Compiled on Arch Linux with Clang version 18.1.8
```
CC = clang
CFLAGS = -MMD -march=native -O2 -Wall -Wextra -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -g
LDFLAGS = -z relro -z now -z noexecstack -fsanitize=address
```
Here I've attached the ASan output and my hostapd-mana conf file
[asan.txt](https://github.com/user-attachments/files/17149238/asan.txt)
[hostapd.conf.txt](https://github.com/user-attachments/files/17149239/hostapd.conf.txt)

**Comment by singe** [comment]
Please submit upstream.
