### ISSUE TITLE
open ssl error. 

### ISSUE THREAD

**Issue by edlovesiraq** [sensepost/hostapd-mana#7]
Hi,
Trying to get the snoopy like functionality from mana. Can't get hostapd-mana to make because of what seems like a SSL error? Any help is appreciated! 
` CC  main.c
  CC  config_file.c
  CC  ../src/ap/hostapd.c
  CC  ../src/ap/wpa_auth_glue.c
  CC  ../src/ap/drv_callbacks.c
  CC  ../src/ap/ap_drv_ops.c
  CC  ../src/ap/utils.c
  CC  ../src/ap/authsrv.c
  CC  ../src/ap/ieee802_1x.c
  CC  ../src/ap/ap_config.c
  CC  ../src/ap/eap_user_db.c
  CC  ../src/ap/ieee802_11_auth.c
  CC  ../src/ap/sta_info.c
  CC  ../src/ap/wpa_auth.c
  CC  ../src/ap/tkip_countermeasures.c
  CC  ../src/ap/ap_mlme.c
  CC  ../src/ap/wpa_auth_ie.c
  CC  ../src/ap/preauth_auth.c
  CC  ../src/ap/pmksa_cache_auth.c
  CC  ../src/ap/ieee802_11_shared.c
  CC  ../src/ap/beacon.c
  CC  ../src/drivers/drivers.c
  CC  ../src/utils/eloop.c
  CC  ../src/utils/common.c
  CC  ../src/utils/wpa_debug.c
  CC  ../src/utils/wpabuf.c
  CC  ../src/utils/os_unix.c
  CC  ../src/utils/ip_addr.c
  CC  ../src/common/ieee802_11_common.c
  CC  ../src/common/wpa_common.c
  CC  ../src/eapol_auth/eapol_auth_sm.c
  CC  ../src/eapol_auth/eapol_auth_dump.c
  CC  ../src/radius/radius.c
  CC  ../src/radius/radius_client.c
  CC  ../src/radius/radius_das.c
  CC  ../src/ap/vlan_init.c
  CC  ctrl_iface.c
  CC  ../src/ap/ctrl_iface_ap.c
  CC  ../src/crypto/md5.c
  CC  ../src/ap/iapp.c
  CC  ../src/ap/peerkey_auth.c
  CC  ../src/drivers/driver_hostap.c
  CC  ../src/drivers/driver_wired.c
  CC  ../src/drivers/driver_nl80211.c
  CC  ../src/utils/radiotap.c
  CC  ../src/drivers/netlink.c
  CC  ../src/drivers/linux_ioctl.c
  CC  ../src/drivers/rfkill.c
  CC  ../src/l2_packet/l2_packet_linux.c
  CC  ../src/eap_server/eap_server_md5.c
  CC  ../src/eap_server/eap_server_tls.c
  CC  ../src/eap_server/eap_server_peap.c
  CC  ../src/eap_common/eap_peap_common.c
../src/eap_server/eap_server_ttls.c: In function ‘eap_ttls_process_phase2_pap’:
../src/eap_server/eap_server_ttls.c:520:22: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 5 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
    fprintf(f, "%s|%*.*s|%s\n", hdr, 0, sm->identity_len, sm->identity, user_password);
                      ^
  CC  ../src/eap_server/eap_server_ttls.c
  CC  ../src/eap_server/eap_server_mschapv2.c
  CC  ../src/eap_server/eap_server_gtc.c
  CC  ../src/eap_server/eap_server_sim.c
  CC  ../src/eap_server/eap_server_aka.c
  CC  ../src/eap_common/eap_sim_common.c
  CC  ../src/eap_server/eap_sim_db.c
  CC  ../src/eap_server/eap_server_pax.c
  CC  ../src/eap_common/eap_pax_common.c
  CC  ../src/eap_server/eap_server_psk.c
  CC  ../src/eap_common/eap_psk_common.c
  CC  ../src/eap_server/eap_server_sake.c
  CC  ../src/eap_common/eap_sake_common.c
  CC  ../src/eap_server/eap_server_gpsk.c
  CC  ../src/eap_common/eap_gpsk_common.c
  CC  ../src/eap_server/eap_server_pwd.c
  CC  ../src/eap_common/eap_pwd_common.c
  CC  ../src/eap_server/eap_server_eke.c
  CC  ../src/eap_common/eap_eke_common.c
  CC  ../src/eap_server/eap_server_fast.c
  CC  ../src/eap_common/eap_fast_common.c
  CC  ../src/eap_server/eap_server_ikev2.c
  CC  ../src/eap_server/ikev2.c
  CC  ../src/eap_common/eap_ikev2_common.c
  CC  ../src/eap_common/ikev2_common.c
  CC  ../src/eap_server/eap_server_tnc.c
  CC  ../src/eap_server/tncs.c
  CC  eap_register.c
../src/eap_server/eap_server.c: In function ‘eap_user_get’:
../src/eap_server/eap_server.c:100:49: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  wpa_printf(MSG_INFO, "MANA (EAP) : identity: %.*s", identity_len, identity);
                                                 ^
  CC  ../src/eap_server/eap_server.c
  CC  ../src/eap_common/eap_common.c
  CC  ../src/eap_server/eap_server_methods.c
  CC  ../src/eap_server/eap_server_identity.c
  CC  ../src/crypto/ms_funcs.c
  CC  ../src/eap_common/chap.c
  CC  ../src/eap_server/eap_server_tls_common.c
../src/crypto/tls_openssl.c: In function ‘tls_init’:
../src/crypto/tls_openssl.c:812:2: warning: ‘TLSv1_method’ is deprecated [-Wdeprecated-declarations]
  ssl = SSL_CTX_new(TLSv1_method());
  ^~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ../src/crypto/tls_openssl.c:19:
/usr/include/openssl/ssl.h:1596:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
../src/crypto/tls_openssl.c: In function ‘tls_deinit’:
../src/crypto/tls_openssl.c:868:3: warning: ‘ERR_remove_thread_state’ is deprecated [-Wdeprecated-declarations]
   ERR_remove_thread_state(NULL);
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ../src/crypto/tls_openssl.c:19:
/usr/include/openssl/err.h:246:1: note: declared here
 DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
 ^
../src/crypto/tls_openssl.c: In function ‘tls_load_ca_der’:
../src/crypto/tls_openssl.c:1540:40: error: dereferencing pointer to incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
  lookup = X509_STORE_add_lookup(ssl_ctx->cert_store,
                                        ^~
../src/crypto/tls_openssl.c: In function ‘tls_connection_get_keys’:
../src/crypto/tls_openssl.c:2532:24: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
  if (ssl == NULL || ssl->s3 == NULL || ssl->session == NULL)
                        ^~
../src/crypto/tls_openssl.c: In function ‘tls_connection_set_session_ticket_cb’:
../src/crypto/tls_openssl.c:3534:44: warning: passing argument 2 of ‘SSL_set_session_secret_cb’ from incompatible pointer type [-Wincompatible-pointer-types]
   if (SSL_set_session_secret_cb(conn->ssl, tls_sess_sec_cb,
                                            ^~~~~~~~~~~~~~~
In file included from ../src/crypto/tls_openssl.c:19:0:
/usr/include/openssl/ssl.h:1799:12: note: expected ‘tls_session_secret_cb_fn {aka int (*)(struct ssl_st *, void *, int *, struct stack_st_SSL_CIPHER *, const struct ssl_cipher_st **, void *)}’ but argument is of type ‘int (*)(SSL *, void *, int *, struct stack_st_SSL_CIPHER *, SSL_CIPHER **, void *) {aka int (*)(struct ssl_st *, void *, int *, struct stack_st_SSL_CIPHER *, struct ssl_cipher_st **, void *)}’
 __owur int SSL_set_session_secret_cb(SSL *s,
            ^~~~~~~~~~~~~~~~~~~~~~~~~
../src/crypto/tls_openssl.c: In function ‘tls_connection_resumed’:
../src/crypto/tls_openssl.c:2819:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:891: recipe for target '../src/crypto/tls_openssl.o' failed
make: *** [../src/crypto/tls_openssl.o] Error 1
`

**Comment by singe** [comment]
I'm too lazy to debug this right now. Any chance you could try the hostapd-2.6 branch and see if that works for you?

**Comment by edlovesiraq** [comment]
Lol! Will do. Hit you back after xmas. Huge fan of your company btw! Merry
Xmas

**Comment by edlovesiraq** [comment]
no luck, same error with that. =(
I'll keep cracking and hit you back if I find a fix.

**Comment by singe** [comment]
This is the same as #8 and I'm going to close this one.
